#include <fstream>
#include <iomanip>
#include <iostream>
#include <sstream>
#include <string>

const char pathToUlm[] = "path-to-ulm";
const char objFile[] = "call_start.o";
const char outFile[] = "call_start.hpp";

int
main(void)
{
    try {
	std::ifstream inPath(pathToUlm);
	if (inPath.fail()) {
	    std::cerr << "can not open '" << pathToUlm << "'" << std::endl;
	    return 1;
	}
	std::ifstream in(objFile);
	if (in.fail()) {
	    std::cerr << "can not open '" << objFile << "'" << std::endl;
	    return 1;
	}
	std::ofstream out(outFile);
	std::string line;

	if (!std::getline(inPath, line)) {
	    std::cerr << "file '" << pathToUlm << "' is empty" << std::endl;
	    return 1;
	}
	if (line.back() == '/') {
	    line.pop_back();
	}
	out << std::setfill(' ') << std::setw(4) << ' '
	    << "std::string ulm = \"" << line << "/ulm\";" << std::endl;

	out << std::setfill(' ') << std::setw(4) << ' '
	    << "std::stringstream ss;" << std::endl;
	while (std::getline(in, line)) {
	    out << std::setfill(' ') << std::setw(4) << ' ' << "ss << \""
		<< line << "\" << std::endl;" << std::endl;
	}
	out << std::setfill(' ') << std::setw(4) << ' '
	    << "objectFile.readSegments(ss, \"generated by ulmld\");"
	    << std::endl;

    } catch (std::exception &e) {
	std::cerr << "execution aborted" << std::endl << e.what() << std::endl;
	std::exit(1);
    }
}
